services:
  db:
    build: ./db
    ports:
      - 5100:5432
    healthcheck:
      # test: ["CMD-SHELL", "pg_isready -U postgres -d career"]
      test: [CMD-SHELL, "./healthcheck.sh"]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 10s
    env_file:
      - ./.env

  web:
    build: ./web
    volumes:
      - ./web:/app:cached
    ports:
      - '8100:8100'
    depends_on:
      db:
        condition: service_healthy
        restart: true
    command: sh -c 'chmod +x ./start_django.sh && chmod +x ./init_django.sh  && ./init_django.sh'
    env_file:
      - ./.env
        
#  sh -c "source /app/venv/bin/activate" && 